site_name: Joseph Tindall
site_url: https://josephtindall.com/
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Dark mode